import Head from 'next/head'
import Image from 'next/image'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillLinkedin}

export default function Home() {
  return (
    <div>
      <Head>
        <title>asif ali portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10' >
        <section className="min-h-screen">
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className="text-xl font-burtons">asif ali.</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill className='cursor-pointer' />
            </li>
            <li>contact</li>
            <li><a href="#"> Resume</a></li>
          </ul>
        </nav>
        <div>
          <h2>asif ali</h2>
          <h3>Developer</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga iusto enim nulla,
             quisquam minus facere corrupti ab libero porro minima inventore voluptatibus voluptates cumque nesciunt quos blanditiis. Laboriosam, ut vero!
          </p>
        </div>
        <AiFillLinkedin />
        
        <div>

        </div>

        </section>
      </main>

      
    </div>
  )
}


